name: Create Release
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Read version from version.txt
        id: read-version
        run: |
          VERSION=$(cat version.txt | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "Creating release $VERSION"
          git tag -a $VERSION -m "Release $VERSION"
          git push origin $VERSION
          gh release create $VERSION --title "TicTacToe $VERSION"
